### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by GSMgo** [GSMgo/Hisentry#1]
- [ ] Fix background color

- [x] Make sign_out work

- [ ] Add facebook and google login / maybe twitter?

- [ ] adapt static views

- [ ] create db mockup
- [ ] Fix alerts -> https://github.com/plataformatec/devise/wiki/How-To:-Integrate-I18n-Flash-Messages-with-Devise-and-Bootstrap

else...
